[env]
term="xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font]
builtin_box_drawing = true
size = 26

[font.offset]
x = 1
y = 8

[scrolling]
history = 100000
multiplier = 4

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
]

[window]
option_as_alt = "Both"
